# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/wjn7/Desktop/full_cpu/Final Project Vivado/Final Project Vivado.runs/synth_1/Wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/wjn7/Desktop/full_cpu/Final Project Vivado/Final Project Vivado.cache/wt} [current_project]
set_property parent.project_path {C:/Users/wjn7/Desktop/full_cpu/Final Project Vivado/Final Project Vivado.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/wjn7/Desktop/full_cpu/Final Project Vivado/Final Project Vivado.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  {C:/Users/wjn7/Desktop/full_cpu/Test Files/Memory Files/fpga_test.mem}
  C:/Users/wjn7/Desktop/full_cpu/final_modules/colors.mem
  C:/Users/wjn7/Desktop/full_cpu/final_modules/image.mem
  {C:/Users/wjn7/Desktop/full_cpu/Test Files/Memory Files/t_gen.mem}
  {C:/Users/wjn7/Desktop/full_cpu/Test Files/Memory Files/genetic.mem}
  {C:/Users/wjn7/Desktop/full_cpu/Test Files/Memory Files/move_test.mem}
  {C:/Users/wjn7/Desktop/full_cpu/Test Files/Memory Files/multigen.mem}
  {C:/Users/wjn7/Desktop/full_cpu/Test Files/Memory Files/nosort.mem}
}
read_verilog -library xil_defaultlib {
  C:/Users/wjn7/Desktop/full_cpu/RAM.v
  C:/Users/wjn7/Desktop/full_cpu/ROM.v
  C:/Users/wjn7/Desktop/full_cpu/final_modules/VGAController.v
  C:/Users/wjn7/Desktop/full_cpu/final_modules/VGATimingGenerator.v
  C:/Users/wjn7/Desktop/full_cpu/final_modules/VGA_RAM.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/add_32bit.v
  C:/Users/wjn7/Desktop/full_cpu/main_modules/alu.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/and_32bit.v
  C:/Users/wjn7/Desktop/full_cpu/array_divider/array_divider_32b.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/cla_8b.v
  C:/Users/wjn7/Desktop/full_cpu/control.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/decoder_5.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/dff_sync_clear.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/dffe_ref.v
  C:/Users/wjn7/Desktop/full_cpu/array_divider/divider_cell.v
  {C:/Users/wjn7/Desktop/full_cpu/Wallace Tree/full_adder.v}
  C:/Users/wjn7/Desktop/full_cpu/hazards.v
  C:/Users/wjn7/Desktop/full_cpu/final_modules/lsfr.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/mod_8_counter.v
  C:/Users/wjn7/Desktop/full_cpu/main_modules/multdiv.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/mux_2.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/mux_2_5b.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/mux_4.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/mux_8.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/or_32bit.v
  C:/Users/wjn7/Desktop/full_cpu/processor.v
  C:/Users/wjn7/Desktop/full_cpu/main_modules/regfile.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/register.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/register_32b.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/s_ext17_32.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/s_ext27_32.v
  C:/Users/wjn7/Desktop/full_cpu/final_modules/seg7_handle.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/sl_16b.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/sl_1b.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/sl_2b.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/sl_4b.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/sl_8b.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/sll_32bit.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/sr_16b.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/sr_1b.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/sr_2b.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/sr_4b.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/sr_8b.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/sra_32bit.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/sub_32bit.v
  C:/Users/wjn7/Desktop/full_cpu/subelements/tff_asyncR.v
  {C:/Users/wjn7/Desktop/full_cpu/Wallace Tree/wallace_32b.v}
  C:/Users/wjn7/Desktop/full_cpu/Wrapper.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/wjn7/Desktop/full_cpu/master.xdc
set_property used_in_implementation false [get_files C:/Users/wjn7/Desktop/full_cpu/master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Wrapper -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Wrapper_utilization_synth.rpt -pb Wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
